TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -Os -g3
ASFLAGS = -g3

# object files

OBJS= main.o $(STARTUP) $(FreeRTOS_obj)

# include common make file

include $(TEMPLATEROOT)/Makefile.common


