TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O0 -g3
ASFLAGS = -g3

# object files

OBJS= main.o SPI.o tm_fonts.o tm_ili9341.o xpt2046.o $(STARTUP) $(FreeRTOS_obj)

# include common make file

include $(TEMPLATEROOT)/Makefile.common


