#include <stm32f411xe.h>
#include "RCC.h"

static inline void rcc_turn_off_PLLI2S_clock(void)
{
	RCC->CR &= ~RCC_CR_PLLI2SON;
	while(RCC->CR & RCC_CR_PLLI2SRDY);
}

static inline void rcc_turn_on_PLLI2S_clock(void)
{
	RCC->CR |= RCC_CR_PLLI2SON; //PLL I2S clock enable
	while (!(RCC->CR & RCC_CR_PLLI2SRDY));
}

void rcc_init_i2s_clock(void)
{
	//PLLI2S
	rcc_set_PLLI2S_clock(RCC_PLLI2S_48000);
}

void rcc_init_clock(void)
{
//	RCC->CR &= ~RCC_CR_PLLON;
//	while(RCC->CR & RCC_CR_PLLRDY);

	PWR->CR |= PWR_CR_VOS_0 | PWR_CR_VOS_1;

	FLASH->ACR |= FLASH_ACR_LATENCY_3WS;

	RCC->PLLCFGR = (RCC->PLLCFGR & ~RCC_PLLCFGR_PLLSRC_Msk) | RCC_PLLCFGR_PLLSRC_HSE;

	//PLLM = 000100 (4)
	RCC->PLLCFGR = (RCC->PLLCFGR & ~RCC_PLLCFGR_PLLM_Msk) | RCC_PLLCFGR_PLLM_2;

	//PLLN = 1100000 (96)
	RCC->PLLCFGR = (RCC->PLLCFGR & ~RCC_PLLCFGR_PLLN_Msk) | RCC_PLLCFGR_PLLN_6 | RCC_PLLCFGR_PLLN_5;

	//PLLP = 00 (2)
	RCC->PLLCFGR = (RCC->PLLCFGR & ~RCC_PLLCFGR_PLLP_Msk);

	//PLLQ = 0100 (4)
	RCC->PLLCFGR = (RCC->PLLCFGR & ~RCC_PLLCFGR_PLLQ_Msk) | RCC_PLLCFGR_PLLQ_2;

	RCC->CFGR |= RCC_CFGR_RTCPRE_3; //HSE divison factor for RTC clock (8)
	RCC->CFGR |= RCC_CFGR_PPRE1_2; //APB1 clock divided by 2

	RCC->CR |= RCC_CR_HSEON; //HSE clock enable
	while(!(RCC->CR & RCC_CR_HSERDY));

	RCC->CR |= RCC_CR_PLLON; //PLL clock enable
	while (!(RCC->CR & RCC_CR_PLLRDY));

	RCC->CFGR |= RCC_CFGR_SW_1; // Select PLL as system clock
	while (!((RCC->CFGR & RCC_CFGR_SWS_1) &&
	         (!(RCC->CFGR & RCC_CFGR_SWS_0)))); // Wait until ready

	SystemCoreClock = 96000000;
}

void rcc_set_PLLI2S_clock(enum RCC_PLLI2S_clock clock)
{
	rcc_turn_off_PLLI2S_clock();
	switch (clock) {
	case RCC_PLLI2S_48000:
		//PLLM = 001000 (8)
		RCC->PLLI2SCFGR = (RCC->PLLI2SCFGR & ~RCC_PLLI2SCFGR_PLLI2SM_Msk) |
				  RCC_PLLI2SCFGR_PLLI2SM_3;
		//N=258
		RCC->PLLI2SCFGR = (RCC->PLLI2SCFGR & ~RCC_PLLI2SCFGR_PLLI2SN_Msk) |
				   RCC_PLLI2SCFGR_PLLI2SN_8 |
				   RCC_PLLI2SCFGR_PLLI2SN_1;
		//R = 3
		RCC->PLLI2SCFGR = (RCC->PLLI2SCFGR & ~RCC_PLLI2SCFGR_PLLI2SR_Msk) |
			           RCC_PLLI2SCFGR_PLLI2SR_1 | RCC_PLLI2SCFGR_PLLI2SR_0;
		break;
	case RCC_PLLI2S_44100:
		//PLLM = 001000 (8)
		RCC->PLLI2SCFGR = (RCC->PLLI2SCFGR & ~RCC_PLLI2SCFGR_PLLI2SM_Msk) |
				  RCC_PLLI2SCFGR_PLLI2SM_3;
		//N=271
		RCC->PLLI2SCFGR = (RCC->PLLI2SCFGR & ~RCC_PLLI2SCFGR_PLLI2SN_Msk) |
				   RCC_PLLI2SCFGR_PLLI2SN_8 |
				   RCC_PLLI2SCFGR_PLLI2SN_3 |
				   RCC_PLLI2SCFGR_PLLI2SN_2 |
				   RCC_PLLI2SCFGR_PLLI2SN_1 |
				   RCC_PLLI2SCFGR_PLLI2SN_0;
		//R = 2
		RCC->PLLI2SCFGR = (RCC->PLLI2SCFGR & ~RCC_PLLI2SCFGR_PLLI2SR_Msk) |
			           RCC_PLLI2SCFGR_PLLI2SR_1;

		break;
	case RCC_PLLI2S_32000:
		//PLLM = 001000 (8)
		RCC->PLLI2SCFGR = (RCC->PLLI2SCFGR & ~RCC_PLLI2SCFGR_PLLI2SM_Msk) |
				  RCC_PLLI2SCFGR_PLLI2SM_3;
		//N=213
		RCC->PLLI2SCFGR = (RCC->PLLI2SCFGR & ~RCC_PLLI2SCFGR_PLLI2SN_Msk) |
				   RCC_PLLI2SCFGR_PLLI2SN_7 |
				   RCC_PLLI2SCFGR_PLLI2SN_6 |
				   RCC_PLLI2SCFGR_PLLI2SN_4 |
				   RCC_PLLI2SCFGR_PLLI2SN_2 |
				   RCC_PLLI2SCFGR_PLLI2SN_0;
		//R = 2
		RCC->PLLI2SCFGR = (RCC->PLLI2SCFGR & ~RCC_PLLI2SCFGR_PLLI2SR_Msk) |
			           RCC_PLLI2SCFGR_PLLI2SR_1;

		break;
	default:
		while(1);
	}
	rcc_turn_on_PLLI2S_clock();
}
